[profile.default]
src = "src"
out = "out"
libs = ["lib"]
test = "test"
script = "script"
solc = "0.8.28"
optimizer = true
optimizer_runs = 200
ffi = false
fs_permissions = [{ access = "read", path = "./" }]
gas_reports = ["LeagueVault", "PositionCard"]

[profile.default.fuzz]
runs = 256

[profile.intense.fuzz]
runs = 2048

[rpc_endpoints]
anvil = "http://127.0.0.1:8545"

[fmt]
line_length = 100
tab_width = 4
bracket_spacing = false
int_types = "long"

[lint]
exclude_lints = ["unsafe-typecast", "block-timestamp"]

[etherscan]
mainnet = { key = "${ETHERSCAN_API_KEY}" }
